name: Build & Release Drawer Opener

on:
  push:
    tags:
      - "v*"          # e.g. v0.2.0
  workflow_dispatch:   # allow manual runs from Actions tab

permissions:
  contents: write      # needed to create releases & upload assets

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build app
        env:
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: "true"
          CSC_IDENTITY_AUTO_DISCOVERY: "false"
          ELECTRON_BUILDER_SKIP_PUBLISH: "true"
        run: npm run build

      - name: Archive macOS artifacts
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macOS-artifacts
          path: |
            dist/*.dmg
            dist/*-mac.zip
          if-no-files-found: warn

      - name: Archive Windows artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            dist/*.exe
            dist/*.msi
          if-no-files-found: warn

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: macOS-artifacts
          path: dist-mac
        continue-on-error: true

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-artifacts
          path: dist-win
        continue-on-error: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist-mac/**
            dist-win/**
          generate_release_notes: true